server:
  port: 8888
spring:
  datasource:
    username: root
    password: gn131313
    url: jdbc:mysql://127.0.0.1:3306/bsp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  type-aliases-package: com.neusoft.bsp.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
